version: "3.8"
services:
  # NOTE: the backend uses an sqllite file-based db for simplicity
  todos-backend:
    build: src/api/
    environment:
      - NODE_ENV=production
    ports:
      - "8008:8008"
  todos-frontend:
    build: src/client/
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=http://todos-backend:8008
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    volumes:
      - .env:/var/www/webapp/static/.env
    ports:
      - "3001:3001"
